Section "InputClass"
    Identifier "Synaptics Touchpad"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "on"
    Option "TappingButtonMap" "lrm"
    Option "NaturalScrolling" "on"
    Option "ClickMethod" "clickfinger"
    Option "MiddleEmulation" "on"
EndSection
