#!/usr/bin/env python3
"""Substrate orchestrator. Runs all agents in sequence and generates a daily briefing.

Usage:
    python3 scripts/agents/orchestrator.py
    python3 scripts/agents/orchestrator.py --date 2026-03-07
    python3 scripts/agents/orchestrator.py --dry-run

Agents run in order:
    1. Byte  (news_researcher.py)     — fetch latest AI news
    2. Echo  (release_tracker.py)     — check for Anthropic releases
    3. Flux  (brainstormer.py)        — brainstorm improvements based on releases
    4. Pixel (visual_artist.py)       — generate images for content
    5. Spore (community_manager.py)   — manage community engagement
    6. Root  (infra_engineer.py)      — monitor infrastructure health
    7. Lumen (educator.py)            — maintain curriculum content
    8. Arc   (arcade_director.py)     — review arcade game quality
    9. Forge (site_engineer.py)       — monitor site health and links
   10. Hum   (audio_director.py)     — scan arcade audio coverage
   11. Sync  (comms_director.py)     — check narrative consistency
   12. Dash  (project_manager.py)     — generate project status report

Output: memory/briefings/YYYY-MM-DD.md
"""

import argparse
import os
import subprocess
import sys
from datetime import datetime

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_DIR = os.path.dirname(os.path.dirname(SCRIPT_DIR))
BRIEFINGS_DIR = os.path.join(REPO_DIR, "memory", "briefings")

# Agent definitions: (name, symbol, script, description)
AGENTS = [
    ("Byte", "B>", "news_researcher.py", "AI News Reporter"),
    ("Echo", "E~", "release_tracker.py", "Release Tracker"),
    ("Flux", "F*", "brainstormer.py", "Innovation Strategist"),
    ("Pixel", "P#", "visual_artist.py", "Visual Artist"),
    ("Spore", "S%", "community_manager.py", "Community Manager"),
    ("Root", "R/", "infra_engineer.py", "Infrastructure Engineer"),
    ("Lumen", "L.", "educator.py", "Educator"),
    ("Arc", "A^", "arcade_director.py", "Arcade Director"),
    ("Forge", "F/", "site_engineer.py", "Site Engineer"),
    ("Hum", "H~", "audio_director.py", "Audio Director"),
    ("Sync", "S=", "comms_director.py", "Communications Director"),
    ("Dash", "D!", "project_manager.py", "Project Manager"),
]


def run_agent(name, script, date_str):
    """Run a single agent script and capture its output.

    Returns (stdout, stderr, returncode).
    """
    script_path = os.path.join(SCRIPT_DIR, script)

    if not os.path.isfile(script_path):
        return "", f"script not found: {script_path}", 1

    cmd = [sys.executable, script_path]
    if date_str:
        cmd.extend(["--date", date_str])

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=120,
            cwd=REPO_DIR,
        )
        return result.stdout.strip(), result.stderr.strip(), result.returncode
    except subprocess.TimeoutExpired:
        return "", f"{name} timed out after 120s", 1
    except Exception as e:
        return "", f"{name} failed: {e}", 1


def generate_briefing(date_str, results):
    """Generate a combined daily briefing from all agent outputs."""
    lines = [
        f"# Daily Briefing: {date_str}",
        "",
        f"Generated by the Substrate orchestrator at {datetime.now().strftime('%H:%M:%S')}.",
        "",
        "---",
        "",
    ]

    for name, symbol, _script, role in AGENTS:
        stdout, stderr, returncode = results[name]
        status = "OK" if returncode == 0 else "FAILED"

        lines.append(f"## [{symbol}] {name} — {role}")
        lines.append("")

        if returncode != 0:
            lines.append(f"**Status:** {status}")
            lines.append("")
            if stderr:
                lines.append(f"Error: {stderr}")
            else:
                lines.append("No output (agent script may not exist yet).")
            lines.append("")
        elif stdout:
            lines.append(stdout)
            lines.append("")
        else:
            lines.append("No output.")
            lines.append("")

        lines.append("---")
        lines.append("")

    lines.append("*End of briefing.*")
    lines.append("")

    return "\n".join(lines)


def print_summary(date_str, results):
    """Print a concise summary to stdout."""
    print(f"\n{'=' * 50}")
    print(f"  SUBSTRATE DAILY BRIEFING — {date_str}")
    print(f"{'=' * 50}\n")

    for name, symbol, _script, role in AGENTS:
        stdout, stderr, returncode = results[name]

        if returncode == 0 and stdout:
            # Show first line of output as summary
            first_line = stdout.split("\n")[0][:70]
            print(f"  [{symbol}] {name:6s} | {first_line}")
        elif returncode != 0:
            reason = stderr.split("\n")[0][:50] if stderr else "no output"
            print(f"  [{symbol}] {name:6s} | FAILED — {reason}")
        else:
            print(f"  [{symbol}] {name:6s} | (no output)")

    print(f"\n{'=' * 50}")


def main():
    parser = argparse.ArgumentParser(description="Substrate orchestrator — run all agents.")
    parser.add_argument(
        "--date", default=None,
        help="Date for the briefing (YYYY-MM-DD, default: today)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print briefing to stdout instead of writing file",
    )
    args = parser.parse_args()

    date_str = args.date or datetime.now().strftime("%Y-%m-%d")

    print(f"[orchestrator] starting daily run for {date_str}", file=sys.stderr)

    # Run each agent in sequence and collect results
    results = {}
    for name, symbol, script, role in AGENTS:
        print(f"[orchestrator] running {name} ({script})...", file=sys.stderr)
        stdout, stderr, returncode = run_agent(name, script, date_str)
        results[name] = (stdout, stderr, returncode)

        if returncode == 0:
            print(f"[orchestrator] {name} completed", file=sys.stderr)
        else:
            print(f"[orchestrator] {name} failed: {stderr[:80]}", file=sys.stderr)

    # Generate the briefing
    briefing = generate_briefing(date_str, results)

    # Print summary to stdout
    print_summary(date_str, results)

    if args.dry_run:
        print("\n--- FULL BRIEFING ---\n")
        print(briefing)
        return

    # Write briefing to file
    os.makedirs(BRIEFINGS_DIR, exist_ok=True)
    filepath = os.path.join(BRIEFINGS_DIR, f"{date_str}.md")

    with open(filepath, "w") as f:
        f.write(briefing)

    print(f"\n[orchestrator] briefing written to {filepath}", file=sys.stderr)
    print(f"[orchestrator] done", file=sys.stderr)


if __name__ == "__main__":
    main()
